routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginAdminController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Guest
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/informasi/{id}/{judul}', [App\Http\Controllers\HomeController::class, 'informasi'])->name('informasi');
Route::get('/jurusan/{id}/{judul}', [App\Http\Controllers\HomeController::class, 'jurusan'])->name('jurusan');

//User
Route::group(['middleware'=>'auth'], function(){    
    Route::get('/dashboard', [App\Http\Controllers\UserDashboardController::class, 'index'])->name('dashboard');
    Route::get('/formulir-pdf', [App\Http\Controllers\UserDashboardController::class, 'formulirPDF'])->name('formulir-pdf');

    Route::get('/cetak-formulir', function(){
        return view('front.cetak-formulir');
    })->name('cetak-formulir');

    Route::get('/profil', function(){
        return view('front.profil');
    })->name('profil');
    
    Route::get('/pendaftaran', function(){
        return view('front.pendaftaran');
    })->name('pendaftaran');
});


//Auth Admin   
Route::get('/admin/login', [LoginAdminController::class, 'showLoginForm'])->name('admin.login');
Route::post('/admin/login', [LoginAdminController::class, 'login'])->name('admin.login.attemp');
Route::post('/admin/logout', [LoginAdminController::class, 'logout'])->name('admin.logout');

//Admin
Route::group(['middleware'=>'admin', 'prefix'=>'/admin', 'as'=>'admin.'], function(){
    Route::get('/', function(){
        return view('admin.dashboard');
    })->name('dashboard');

    Route::get('/profil', function(){
        return view('admin.profil');
    })->name('profil');

    Route::get('/jurusan', function(){
        return view('admin.jurusan');
    })->name('jurusan');

    Route::get('/periode', function(){
        return view('admin.periode');
    })->name('periode');

    Route::get('/informasi', function(){
        return view('admin.informasi');
    })->name('informasi');

    Route::get('/slide', function(){
        return view('admin.slide');
    })->name('slide');

    Route::get('/widget', function(){
        return view('admin.widget');
    })->name('widget');

    Route::get('/pendaftar', function(){
        return view('admin.pendaftar');
    })->name('pendaftar');
});

app/Http/Livewire/Front/FormulirPendaftaran.php
<?php

namespace App\Http\Livewire\Front;

use Livewire\Component;
use App\Models\Pendaftar;
use App\Models\Periode;
use App\Models\Jurusan;
use Auth;
class FormulirPendaftaran extends Component
{
    //deklarasi semua properti
    public $id_pendaftar;
    public $id_user;
    public $id_jurusan;
    public $id_periode;
    public $no_pendaftar;
    public $status_seleksi = 'Belum Dikonfirmasi';
    public $nama;
    public $nisn;
    public $tempat_lahir;
    public $tanggal_lahir;
    public $jenis_kelamin = 'L';
    public $anak_ke;
    public $jumlah_saudara;
    public $agama;
    public $hp;
    public $hobi;
    public $cita_cita;

    public $jenis_tempat_tinggal;
    public $alamat;
    public $desa;
    public $kecamatan;
    public $kota;
    public $propinsi;
    public $rt;
    public $rw;
    public $kode_pos;
    public $jarak;
    public $transportasi;

    public $no_kk;
    public $nama_kk;
    public $no_kks;
    public $no_pkh;
    public $no_kip;
    public $nama_ayah;
    public $nik_ayah;
    public $tahun_lahir_ayah;
    public $status_ayah;
    public $pekerjaan_ayah;
    public $penghasilan_ayah;
    public $pendidikan_ayah;
    public $nama_ibu;
    public $nik_ibu;
    public $tahun_lahir_ibu;
    public $status_ibu;
    public $pekerjaan_ibu;
    public $penghasilan_ibu;
    public $pendidikan_ibu;
    public $nama_wali;
    public $nik_wali;
    public $tahun_lahir_wali;
    public $status_wali;
    public $pekerjaan_wali;
    public $penghasilan_wali;
    public $pendidikan_wali;
    public $hp_wali;

    public $nama_sekolah;
    public $jenjang_sekolah;
    public $status_sekolah;
    public $lokasi_sekolah;
    public $tahun_lulus;
    public $no_un;
    public $prestasi;

    public $step = 0;

    //menentukan nilai awal properti sesuai setatus pendaftaran (baru atau edit)
    public function __construct(){
        $this->id_user = Auth::user()->id;
        $this->nama = Auth::user()->name;

        //cek periode aktif
        $periode = Periode::where('aktif','=', 'Y')->first();
        if($periode) $this->id_periode = $periode->id;

        $siswa = Pendaftar::where('id_user', '=', $this->id_user)->first();
        if($siswa){
            $this->id_pendaftar = $siswa->id;

            $this->id_jurusan = $siswa->id_jurusan;
            $this->nisn = $siswa->nisn;
            $this->tempat_lahir = $siswa->tempat_lahir;
            $this->tanggal_lahir = $siswa->tanggal_lahir;
            $this->jenis_kelamin = $siswa->jenis_kelamin;
            $this->anak_ke = $siswa->anak_ke;
            $this->jumlah_saudara = $siswa->jumlah_saudara;
            $this->agama = $siswa->agama;
            $this->hp = $siswa->hp;
            $this->hobi = $siswa->hobi;
            $this->cita_cita = $siswa->cita_cita;

            $this->jenis_tempat_tinggal = $siswa->jenis_tempat_tinggal;
            $this->alamat = $siswa->alamat;
            $this->desa = $siswa->desa;
            $this->kecamatan = $siswa->kecamatan;
            $this->kota = $siswa->kota;
            $this->propinsi = $siswa->propinsi;
            $this->rt = $siswa->rt;
            $this->rw = $siswa->rw;
            $this->kode_pos = $siswa->kode_pos;
            $this->jarak = $siswa->jarak;
            $this->transportasi = $siswa->transportasi;


            $this->no_kk = $siswa->no_kk;
            $this->nama_kk = $siswa->nama_kk;
            $this->no_kks = $siswa->no_kks;
            $this->no_pkh = $siswa->no_pkh;
            $this->no_kip = $siswa->no_kip;
            $this->nama_ayah = $siswa->nama_ayah;
            $this->nik_ayah = $siswa->nik_ayah;
            $this->tahun_lahir_ayah = $siswa->tahun_lahir_ayah;
            $this->status_ayah = $siswa->status_ayah;
            $this->pekerjaan_ayah = $siswa->pekerjaan_ayah;
            $this->penghasilan_ayah = $siswa->penghasilan_ayah;
            $this->pendidikan_ayah = $siswa->pendidikan_ayah;
            $this->nama_ibu = $siswa->nama_ibu;
            $this->nik_ibu = $siswa->nik_ibu;
            $this->tahun_lahir_ibu = $siswa->tahun_lahir_ibu;
            $this->status_ibu = $siswa->status_ibu;
            $this->pekerjaan_ibu = $siswa->pekerjaan_ibu;
            $this->penghasilan_ibu = $siswa->penghasilan_ibu;
            $this->pendidikan_ibu = $siswa->pendidikan_ibu;
            $this->nama_wali = $siswa->nama_wali;
            $this->nik_wali = $siswa->nik_wali;
            $this->tahun_lahir_wali = $siswa->tahun_lahir_wali;
            $this->status_wali = $siswa->status_wali;
            $this->pekerjaan_wali = $siswa->pekerjaan_wali;
            $this->penghasilan_wali = $siswa->penghasilan_wali;
            $this->pendidikan_wali = $siswa->pendidikan_wali;
            $this->hp_wali = $siswa->hp_wali;


            $this->nama_sekolah = $siswa->nama_sekolah;
            $this->jenjang_sekolah = $siswa->jenjang_sekolah;
            $this->status_sekolah = $siswa->status_sekolah;
            $this->lokasi_sekolah = $siswa->lokasi_sekolah;
            $this->tahun_lulus = $siswa->tahun_lulus;
            $this->no_un = $siswa->no_un;
            $this->prestasi = $siswa->prestasi;
        }
    }

    //render view blade
    public function render()
    {
        $jurusan = Jurusan::all();
        $periode = Periode::where('aktif','=', 'Y')->first();
        return view('livewire.front.formulir-pendaftaran', [
            'jurusan' => $jurusan,
            'periode' => $periode
        ]);
    }

    public function save(){
        $periode = Periode::where('aktif','=','Y')->first();
        if($this->step == 0){//cek tahapan pendaftaran
            //validasi tahap pertama
            $this->validate([
                'id_user' => 'required',
                'id_jurusan' => 'required',
                'id_periode' => 'required',
                'status_seleksi' => 'required',
                'nama' => 'required',
                'nisn' => 'required',
                'tempat_lahir' => 'required',
                'tanggal_lahir' => 'required',
                'jenis_kelamin' => 'required',
                'anak_ke' => 'required',
                'jumlah_saudara' => 'required',
                'agama' => 'required',
                'hp' => 'required',
                'hobi' => 'required',
                'cita_cita' => 'required',
            ]);

            //cek data pendaftar dan tentukan mode penyimpanan
            $siswa = Pendaftar::where('id_user', '=', $this->id_user)->first();
            $save_mode = ($siswa) ? 'update' : 'create';

            //pengaturan jika mode simpan create
            if($save_mode == 'create'){
                $siswa = new Pendaftar;

                $max = Pendaftar::where('id_periode','=',$periode->id)->max('no_pendaftar');
                $siswa->no_pendaftar = $max+1;
            }

            //simpan data tahap pertama
            $siswa->id_user = $this->id_user;
            $siswa->id_jurusan = $this->id_jurusan;
            $siswa->id_periode = $this->id_periode;
            $siswa->status_seleksi = $this->status_seleksi;
            $siswa->nama = $this->nama;
            $siswa->nisn = $this->nisn;
            $siswa->tempat_lahir = $this->tempat_lahir;
            $siswa->tanggal_lahir = $this->tanggal_lahir;
            $siswa->jenis_kelamin = $this->jenis_kelamin;
            $siswa->anak_ke = $this->anak_ke;
            $siswa->jumlah_saudara = $this->jumlah_saudara;
            $siswa->agama = $this->agama;
            $siswa->hp = $this->hp;
            $siswa->hobi = $this->hobi;
            $siswa->cita_cita = $this->cita_cita;

            //simpan data sesuai mode penyimpanan
            if($save_mode == 'create') $siswa->save();
            else $siswa->update();

        }elseif($this->step == 1){
            //validasi penyimpanan tahapan kedua
            $this->validate([
                'jenis_tempat_tinggal' => 'required',
                'alamat' => 'required',
                'desa' => 'required',
                'kecamatan' => 'required',
                'kota' => 'required',
                'propinsi' => 'required',
                'rt' => 'required',
                'rw' => 'required',
                'kode_pos' => 'required',
                'jarak' => 'required',
                'transportasi' => 'required',
            ]);

            //simpan data tahapan kedua
            $siswa = Pendaftar::find($this->id_pendaftar);
            $siswa->jenis_tempat_tinggal = $this->jenis_tempat_tinggal;
            $siswa->alamat = $this->alamat;
            $siswa->desa = $this->desa;
            $siswa->kecamatan = $this->kecamatan;
            $siswa->kota = $this->kota;
            $siswa->propinsi = $this->propinsi;
            $siswa->rt = $this->rt;
            $siswa->rw = $this->rw;
            $siswa->kode_pos = $this->kode_pos;
            $siswa->jarak = $this->jarak;
            $siswa->transportasi = $this->transportasi;            
            $siswa->update();

        }elseif($this->step == 2){
            //validasi tahapan ketiga
            $this->validate([
                'no_kk' => 'required',
                'nama_kk' => 'required',
                'nama_ayah' => 'required',
                'nik_ayah' => 'required',
                'tahun_lahir_ayah' => 'required',
                'status_ayah' => 'required',
                'pekerjaan_ayah' => 'required',
                'penghasilan_ayah' => 'required',
                'pendidikan_ayah' => 'required',
                'nama_ibu' => 'required',
                'nik_ibu' => 'required',
                'tahun_lahir_ibu' => 'required',
                'status_ibu' => 'required',
                'pekerjaan_ibu' => 'required',
                'penghasilan_ibu' => 'required',
                'pendidikan_ibu' => 'required',
            ]);

            //simpan data tahapan ketiga
            $siswa = Pendaftar::find($this->id_pendaftar);
            $siswa->no_kk = $this->no_kk;

app/Http/Livewire/Front/ProfilUser.php
<?php

namespace App\Http\Livewire\Front;

use Livewire\Component;
use Illuminate\Support\Facades\Hash;
use Auth;

class ProfilUser extends Component
{
    //deklarasi properti
    public $name;
    public $email;
    public $password;
    public $confirm_password;

    //menentukan nilai awal properti
    public function __construct()
    {
        $this->name = Auth::user()->name;
        $this->email = Auth::user()->email;
    }

    //render view blade
    public function render()
    {
        return view('livewire.front.profil-user');
    }

    public function save(){
        //validasi sebelum update data
        $this->validate([
            'name' => 'required',
            'email' => 'required',
            'confirm_password' => 'same:password',
        ]);

        //update data
        $user = Auth::user();
        $user->name = $this->name;
        $user->email = $this->email;
        if($this->password) $user->password = Hash::make($this->password);
        $user->update();

        //kirim pesan keberhasilan melalui event browser
        $this->dispatchBrowserEvent('show-message',['msg'=>'Data telah disimpan']);
        
        //reset data
        $this->password = null;
        $this->confirm_password = null;
    }
}

app/View/Components/FrontLyout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use App\Models\Periode;

class FrontLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        //kirimkan periode aktif untuk mengecek status pendaftaran dibuka atau belum
        $periode = Periode::where('aktif','=','Y')->first();
        return view('layouts.front',['periode'=>$periode]); 
    }
}

resources/views/front/cetak-formulir.blade.php
<x-front-layout>
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            
    <div class="row">
        <div class="col-md-4">
            <x-front-widget posisi="Samping"></x-front-widgt>
        </div>
        <div class="col-md-8">
            
            <h5 class="text-primary page-title">Cetak Formulir</h5>
        
            <!-- iframe untuk menampilkan PDF -->
            <iframe style="
                width: 100%;
                height: calc(100vh - 230px);
            " src="/formulir-pdf" id="pdf"></iframe>

            <a href="/dashboard" class="btn btn-secondary text-white float-start">
                <i class="fas fa-chevron-left"></i> Kembali
            </a>
            <!-- membuat tombol yang dapat print dokumen pada iframe -->
            <a class="btn btn-primary text-white float-end" onclick="
                pdf = document.getElementById('pdf').contentWindow;
                pdf.focus();
                pdf.print();"
            >
                <i class="fas fa-print"></i> Cetak
            </a>
               
        </div>
    </div>

        </div>
    </div>
</div>

<x-slot name="footer">
    <x-front-widget posisi="Bawah"></x-front-widget>
</x-slot>
</x-front-layout>

resources/views/front/dashboard.blade.php
<x-front-layout>
<div class="container mt-4">
    <div class="card">
        <div class="card-body">

    <div class="row">
        <!-- menampilkan widget dengan posisi samping -->
        <div class="col-md-4 sidebar-widget">
            <x-front-widget posisi="Samping"></x-front-widgt>
        </div>

        <div class="col-md-8">
            <h5 class="page-title">Dashboard User</h5>

<table class="mb-3">
    <tr><td>No. Pendaftar</td><td>:</td><td><b>{{$pendaftar->periode->tahun.(substr('0000'.$pendaftar->no_pendaftar,-4))}}</b></td></tr>
    <tr><td>Nama</td><td>:</td><td> {{$pendaftar->nama}}</td></tr>
    <tr><td>NISN</td><td>:</td><td> {{$pendaftar->nisn}}</td></tr>
    <tr><td>Tempat/Tanggal Lahir</td><td>:</td><td> {{$pendaftar->tempat_lahir}}, {{$pendaftar->tanggal_lahir}}</td></tr>
    <tr><td>Jenis Kelamin</td><td>:</td><td> {{$pendaftar->jenis_kelamin}}</td></tr>
    <tr><td valign="top">Alamat</td><td>:</td>
        <td> 
            {{$pendaftar->alamat}} <br>
            Desa: {{$pendaftar->desa}} RT: {{$pendaftar->rt}} RT: {{$pendaftar->rw}} <br>
            Kec: {{$pendaftar->kecamatan}} Kab./Kota: {{$pendaftar->kota}}<br>
            Prov.: {{$pendaftar->propinsi}} Kode pos: {{$pendaftar->kode_pos}}<br>
        </td>
    </tr>
    <tr><td>Agama</td><td>:</td><td> {{$pendaftar->agama}}</td></tr>
    <tr><td>Pilihan Jurusan</td><td>:</td><td> {{$pendaftar->jurusan->nama_jurusan}}</td></tr>
    <tr><td>Tanggal Daftar</td><td>:</td><td> {{ $pendaftar->created_at->isoFormat('dddd, D MMMM Y') }}</td></tr>
    <tr><td>Hasil Seleksi</td><td>:</td><td><b> {{ strtoupper($pendaftar->status_seleksi) }} </b></td></tr>
</table>

<a href="/cetak-formulir" class="btn btn-primary me-2 text-white">
    <i class="fas fa-print"></i> Cetak Formulir
</a>
<a href="/pendaftaran" class="btn btn-primary me-2 text-white">
    <i class="fas fa-edit"></i> Edit Formulir
</a>

        </div>
    </div>

        </div>
    </div>
</div>

<!-- menampilkan widget dg posisi bawah -->
<x-slot name="footer">
    <x-front-widget posisi="Bawah"></x-front-widget>
</x-slot>
</x-front-layout>

resources/views/front/home.blade.php
<x-front-layout>

<!-- slideshow gambar -->
<div class="bg-dark pt-3 pb-2">
    <div class="container">
        <div  x-data x-init="new Splide($refs.splide, {
        type: 'loop',
        height : 'calc(100vh - 220px)',   
        cover: true,   
        autoplay : true,   
        }).mount();">
            <div class="splide" x-ref="splide">
                <div class="splide__track">
                    <ul class="splide__list">
                        @foreach($slide as $s)                     
                            <li class="splide__slide" style="text-shadow: 0 0 5px #000">
                                <img src="/storage/slide/{{$s->gambar}}" alt="">
                                <h1 class="text-center text-white" style="margin-top: calc(50vh - 150px); font-size: 50px">{{$s->judul}}</h1>
                                <div class="text-center text-white d-none d-md-block"> 
                                    <h5 style="padding: 0 100px">{{$s->deskripsi}}</h5>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- menampilkan status dibukanya pendaftaran-->
<div class="bg-secondary">
    <div class="container">
        <div class="row pt-4 pb-4">
            <div class="col-md-12 text-white text-center">
        @if($periode and Carbon\Carbon::now()->isBetween($periode->tanggal_buka, $periode->tanggal_tutup))
            <h3>Pendaftaran peserta didik baru telah dibuka</h3>
            
            <a href="/register" class="btn btn-primary mb-2">
               <i class="fas fa-edit"></i> Daftar Sekarang
            </a>           
        @elseif($periode and Carbon\Carbon::now()->isAfter($periode->tanggal_buka))
            <h3>Pendaftaran peserta didik baru telah ditutup</h3>
        @else
            <h3>Pendaftaran peserta didik baru belum dibuka</h3>            
        @endif
            
            <span id="informasi"></span>
            <a @click="document.getElementById('informasi').scrollIntoView()" class="btn btn-primary mb-2">
               <i class="fas fa-info-circle"></i> Informasi Pendaftaran
            </a>
            </div>
        </div>
    </div>
</div>

<div class="container mt-4" >
    <div class="card">
        <div class="card-body">

    <div class="row">
        <!-- menampilkan widget dengan posisi samping -->
        <div class="col-md-4 sidebar-widget">
            <x-front-widget posisi="Samping"></x-front-widgt>
        </div>

        <!-- menampilkan informasi pada bagian konten -->
        <div class="col-md-8">
            @foreach($informasi as $i)
                <h5 class="page-title">{{$i->judul}}</h5>
                
                {!! $i->konten !!}
                
            @endforeach
        </div>
    </div>

        </div>
    </div>
</div>

<!-- menampilkan widget dengan posisi bawah -->
<x-slot name="footer">
    <x-front-widget posisi="Bawah"></x-front-widget>
</x-slot>
</x-front-layout>

resources/views/front/informasi.blade.php
<x-front-layout>
<div class="container mt-4">
    <div class="card">
        <div class="card-body">

    <div class="row">
        <!-- menampilkan widget dengan posisi samping -->
        <div class="col-md-4 sidebar-widget">
            <x-front-widget posisi="Samping"></x-front-widgt>
        </div>

        <!-- menampilkan detail informasi pada bagian komponen -->
        <div class="col-md-8">
            <h5 class="page-title">{{$informasi->judul}}</h5>
                    
            {!! $informasi->konten !!}
                
        </div>
    </div>

        </div>
    </div>
</div>

<!-- menampilkan widget dengan posisi bawah -->
<x-slot name="footer">
    <x-front-widget posisi="Bawah"></x-front-widget>
</x-slot>
</x-front-layout>

resources/views/front/jurusan.blade.php
<x-front-layout>
<div class="container mt-4">
    <div class="card">
        <div class="card-body">

    <div class="row">
        <!-- menampilkan widget dengan posisi samping -->
        <div class="col-md-4 sidebar-widget">
            <x-front-widget posisi="Samping"></x-front-widgt>
        </div>

        <!-- menampilkan deskripsi jurusan pada bagian samping -->
        <div class="col-md-8">
            <h5 class="page-title">{{$jurusan->nama_jurusan}}</h5>

            {!! $jurusan->deskripsi !!}
                
        </div>
    </div>

        </div>
    </div>
</div>

<!-- menampilkan widget dengan posisi bawah -->
<x-slot name="footer">
    <x-front-widget posisi="Bawah"></x-front-widget>
</x-slot>
</x-front-layout>

resources/views/front/pendaftaran.blade.php
<x-front-layout>
<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-md-12">
            <livewire:front.formulir-pendaftaran />
        </div>
    </div>
</div>
</x-front-layout>

resources/views/front/profil.blade.php
<x-front-layout>
<div class="container mt-4">
    <div class="card">
        <div class="card-body">

    <div class="row">
         <!-- menampilkan widget dengan posisi samping -->
        <div class="col-md-4 sidebar-widget">
            <x-front-widget posisi="Samping"></x-front-widgt>
        </div>
        <div class="col-md-8">
            <h5 class="page-title">Profil User</h5>

            <livewire:front.profil-user />
        </div>
    </div>

        </div>
    </div>
</div>

<!-- menampilkan widget dengan posisi bawah -->
<x-slot name="footer">
    <x-front-widget posisi="Bawah"></x-front-widget>
</x-slot>
</x-front-layout>